In [1]:
import numpy as np
from scipy.linalg import expm, logm
import openqcs as op
from openqcs.tools import color_matrix, get_su2_param, su2, diagonalize
from openqcs.iterativ import get_iterative_kraus_op
import time

In [2]:
X = np.matrix([[0,1],[1,0]])
Z = np.matrix([[1,0],[0,-1]])
Id = np.matrix(np.eye(2))
a = 0.5
b = 0.5
dt=0.01

def H_(a,b):
    return -a * np.kron(Z, Z) + b*(np.kron(X,Id) + np.kron(Id, X))

def T_(H, dt):
    if not isinstance(H, np.matrix):
        raise ValueError()
    return np.matrix(expm(-1j*H*dt))

H = H_(a,b)
T = T_(H, dt)

In [3]:
rho0 = np.matrix([[1,0],[0,0]])

for i in range(10):
    
    Ks = op.get_kraus_(T**(i))
    rho = op.channel_(rho0, Ks)
    
    print(np.linalg.eigh(rho))

(array([0., 1.]), matrix([[0.+0.j, 1.+0.j],
        [1.+0.j, 0.+0.j]]))
(array([6.94425054e-15, 1.00000000e+00]), matrix([[ 4.99995833e-03+0.j       , -9.99987500e-01-0.j       ],
        [ 4.99991667e-03+0.999975j ,  2.49996875e-05+0.0049999j]]))
(array([4.4439116e-13, 1.0000000e+00]), matrix([[ 9.99966665e-03+0.j        , -9.99950002e-01-0.j        ],
        [ 9.99933336e-03+0.99990001j,  9.99949999e-05+0.00999917j]]))
(array([5.06113323e-12, 1.00000000e+00]), matrix([[ 1.49988749e-02+0.j        , -9.99887511e-01-0.j        ],
        [ 1.49977502e-02+0.99977503j,  2.24974686e-04+0.01499719j]]))
(array([2.84307943e-11, 1.00000000e+00]), matrix([[ 1.99973328e-02+0.j        , -9.99800033e-01-0.j        ],
        [ 1.99946676e-02+0.99960008j,  3.99919993e-04+0.01999333j]]))
(array([1.08425592e-10, 1.00000000e+00]), matrix([[ 2.49947900e-02+0.j        , -9.99687581e-01-0.j        ],
        [ 2.49895863e-02+0.9993752j ,  6.24804663e-04+0.02498698j]]))
(array([3.23650255e-10, 1.00000000